app:
  build: .
  dockerfile: Dockerfile
  command: rails s -b 0.0.0.0
  volumes:
    - .:/app
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp:/tmp
  ports:
    - "3000"
  environment:
    - MONGODB_HOST=${APP_NAME}_mongodb_1:27017
    - IMAGE_NAME=rspec-nonroot

ui:
  build: ../sandbox-ui
  dockerfile: Dockerfile
  command: gulp serve
  volumes:
    - .:/app
  ports:
    - "3000:3000"
    - "3001:3001"
  environment:
    - API_URL=http://${APP_NAME}_app_1:3000
  volumes:
     - "../sandbox-ui:/src"

mongodb:
  image: dockerfile/mongodb
  command: mongod --smallfiles
  volumes:
    - ./db/mongodb:/data/db
  ports:
    - "27017"
