# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 359358dbf51d3a2984691921606ee48ba57f747fb057a290ea455a296f2d0acc0526e80d1efb83b938656babc7b61f8d7e9697db932785c44ef6944bbc55417a

test:
  secret_key_base: 436bcc78703b59413f640471805c222f2b0590f45bd727ae1fec990b5f603b50acf5a6b98f4cbc4c275db00504d61c6889b577e5b9580edd8aa41d773bb430d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
